export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_PRODUCT_SUCCESS = 'SELECT_PRODUCT_SUCCESS';
export const SELECT_PRODUCT_ERROR = 'SELECT_PRODUCT_ERROR'
