export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const SELECT_MOVIE = 'SELECT_MOVIE';
export const SELECT_MOVIE_SUCCESS = 'SELECT_MOVIE_SUCCESS';
export const SELECT_MOVIE_ERROR = 'SELECT_MOVIE_ERROR'
